FROM php:8.2-apache


RUN groupadd -g 1000 admin && useradd -u 1000 -g admin -m admin 

WORKDIR /var/www/html


COPY code/ . 


RUN chown -R admin:www-data /var/www/html && chmod -R 775 /var/www/html 


RUN usermod -aG www-data admin 


EXPOSE 80 


RUN a2enmod rewrite 


USER admin
