---
- name: Install LAMP Stack
  hosts: all
  become: yes
  vars_files:
    - vars/secrets.yml  # For encrypted passwords

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Apache
      package:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: present

    - name: Install MySQL
      package:
        name: "{{ 'mysql-server' if ansible_os_family == 'Debian' else 'mariadb-server' }}"
        state: present

    - name: Install PHP
      package:
        name: "{{ ['php'] + php_modules }}"
        state: present
      vars:
        php_modules:
          - php-mysql
          - libapache2-mod-php
          - php-cli

    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        - "{{ 'mysql' if ansible_os_family == 'Debian' else 'mariadb' }}"
